### ISSUE TITLE
unable to connect to entity system recognizer

### ISSUE THREAD

**Issue by 16mi** [cisco/mindmeld#105]
i am very new at this, please forgive me if you find something odd
initially
mindmeld num-parse --start not working
it was giving error same as mentioned on your page of OS incompatibility of duckling executable
even tried pulling duckling master and also tried running it on port 7151
there's only one halt with the statement as below:
Listening on http://0.0.0.0:7151
and was not responding
then i installed rasa duckling
and it worked fine
but now the python -m food_ordering build command
is giving me error of not able to connect to entity recognizer, even though my num-parser is working fine with an pid of 8154
its just one more warning for DeprecationWarning: numpy.core.umath_tests is an internal NumPy module

 
can u please help me out with this

**Comment by minhtuev** [comment]
hi, has this issue been addressed>

**Comment by minhtuev** [comment]
Closing after the reporter does not address the following-up question
