### ISSUE TITLE
Mapping issue with ES7

### ISSUE THREAD

**Issue by minhtuev** [cisco/mindmeld#137]
As of ES 7, mapping types have been removed. You can read more details here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

This might cause an issue with existing ES filter. Need to reproduce this issue locally for testing.

**Comment by minhtuev** [comment]
@arushir should address this in https://github.com/cisco/mindmeld/pull/147

**Comment by arushir** [comment]
Yes I've addressed it

**Comment by minhtuev** [comment]
@arushir: I just added that as a status update to this issue :)
