### ISSUE TITLE
Date Not Recognized - Question Answerer Filter

### ISSUE THREAD

**Issue by KKsharma99** [cisco/mindmeld#19]
Trying to filter a Date of Birth column 'dob' by comparing it to another date using the Question Answerer filter. There is an error, it seems that mindmeld does not recognize that the 'dob' field is a Date.

Code ==========
s = qa.build_search(index='user_data_3')
s.filter(field='dob', lte='2014-03-03').execute()

Error ===========
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-461-ae515428ae0b> in <module>
----> 1 s.filter(field='dob', lte=kb['doh'][3]).execute()

/anaconda3/envs/mindmeld2/lib/python3.6/site-packages/mindmeld/components/question_answerer.py in filter(self, **kwargs)
    484         """
    485         new_search = self._clone()
--> 486         new_search._build_clause("filter", **kwargs)
    487 
    488         return new_search

/anaconda3/envs/mindmeld2/lib/python3.6/site-packages/mindmeld/components/question_answerer.py in _build_clause(self, clause_type, **kwargs)
    417             self._build_query_clause(**kwargs)
    418         elif clause_type == "filter":
--> 419             self._build_filter_clause(**kwargs)
    420         elif clause_type == "sort":
    421             self._build_sort_clause(**kwargs)

/anaconda3/envs/mindmeld2/lib/python3.6/site-packages/mindmeld/components/question_answerer.py in _build_filter_clause(self, **kwargs)
    383                 raise ValueError('Invalid knowledge base field \'{}\''.format(key))
    384             clause = Search.FilterClause(field=key, value=value)
--> 385         clause.validate()
    386         self._clauses[clause.get_type()].append(clause)
    387 

/anaconda3/envs/mindmeld2/lib/python3.6/site-packages/mindmeld/components/question_answerer.py in validate(self)
    847                 elif not self.field_info.is_number_field() and not self.field_info.is_date_field():
    848                     raise ValueError(
--> 849                         'Range filter can only be defined for number or date field.')
    850 
    851     class SortClause(Clause):

ValueError: Range filter can only be defined for number or date field.

Sample Data =========
 { 'money': 42.0,
  'dob': '1976-11-15',
  'employee_source': 'Other'}

**Comment by minhtuev** [comment]
It seems the issue is not with the actual `lte` param but with the `dob` field. Check : `self._kb_field_info.get(field)` to see what is the field type; you can also do range filter if the field type is number or date.

**Comment by KKsharma99** [comment]
we are sure that dob is not being recognized as a date type since _ValueError: Range filter can only be defined for number or date field_. Current dob values are 'YYYY-MM-DD', how can we ensure that mindmeld processes this string as a date type?

**Comment by ritvikshrivastava** [comment]
This issue occurs with Elasticsearch 6 (6.7 as mentioned in the docs).
When using Elasticsearch 5, the strings are being recognized as a date field in the knowledge base.

**Comment by KKsharma99** [comment]
Recreating the indexes in Elastic Search resolved the issue. This is not an issue with mindmeld. (When the date columns were first made, they were not in the right date format so they were indexed as strings. Even after changing the dates to the right format, the indexes still consider the date columns as strings, the initial assignment. Recreating the index resolves.)
