### ISSUE TITLE
Tokenizer as a configurable service

### ISSUE THREAD

**Issue by minhtuev** [cisco/mindmeld#195]
We want to run the tokenizer as a separate configurable service, similar to Duckling. In this way we can easily switch the tokenizers and have multiple tokenizer services running.

**Comment by minhtuev** [comment]
This is required for German and Japanese languages.

**Comment by vijay120** [comment]
https://github.com/cisco/mindmeld/pull/290 addressed this issue. Phase 1 has been merged.
