### ISSUE TITLE
Does mindmeld support pre-defined entity resolver?

### ISSUE THREAD

**Issue by veeraelluru** [cisco/mindmeld#202]
Entities in the given sentence are classified after modelling entity recogniser using `nlp.build()` with a predefined blue-print or with our own data. But, is there a way to evaluate default entity resolver for pre-defined entities like `sys_date` and `sys_number`.

--Veera.

**Comment by serapio** [comment]
Are you looking for an evaluation of system entities in the app separate from the custom entities? Or are you looking for system entities that are pretrained on some generic data? The training is for the entity recognition (spans and types), and the entity resolution is based on heuristics.

**Comment by minhtuev** [comment]
Closing this issue since there is no further activity - feel free to reopen them if you need to tackle anything
