### ISSUE TITLE
Why can't I "import py" using python3?

### ISSUE THREAD

**Issue by derekmpham** [cisco/mindmeld#212]
Having trouble building my models for application (viet_kwik_e_mart), even when using python3 virtual env.

Running into `ModuleNotFoundError: No module named 'py'` due to `import py` in mindmeld/_util.py. See attached screenshot

<img width="681" alt="Screen Shot 2020-08-23 at 7 10 46 PM" src="https://user-images.githubusercontent.com/16676809/91011118-95d86d00-e598-11ea-9d4b-5a7fe6dd241e.png">

**Comment by minhtuev** [comment]
Can you include the steps to reproduce this issue?

**Comment by serapio** [comment]
It looks like the dependencies weren't installed in your new virtualenv. Try running
```
cd ~/mindmeld
pip install -e .
pip install -r dev-requirements.txt
pip install -r test-requirements.txt
```

**Comment by derekmpham** [comment]
Got it, deploying the models works for me now. Thank you so much Lucien!! 🙏🏻🙏🏻🙏🏻
