### ISSUE TITLE
Classifying role to null when there is a single role under an intent

### ISSUE THREAD

**Issue by sameerg07** [cisco/mindmeld#214]
I have an entity x which has two roles x1 and x2 . x1 is used in an intent i1 and x2 is used in an intent i2 . All the expressions in i1 and i2 have single roles mapped in their expressions for an entity. Now, when I do nlp.process(<expression which has an entity with a single role>), it classifies the role of that entity to null. 

I understand that there is a lazy evaluation happening to avoid role classification, but readability wise it confuses me atleast, that why is my role being shown as null? 

Sample response:
```
{
  "result": {
    "domain": "restaurant",
    "entities": [
      {
        "role": null,
        "span": {
          "end": 8,
          "start": 6
        },
        "text": "one",
        "type": "sys_number",
        "value": [
          {
            "value": 1
          }
        ]
      },
      {
        "role": null,
        "span": {
          "end": 29,
          "start": 10
        },
        "text": "paneer butter masala",
        "type": "dish",
        "value": []
      }
    ],
    "intent": "order",
    "text": "order one paneer butter masala"
  },
  "status": "success"
}
```

where my query is `order one paneer butter masala` which is basically `order {one|sys_number|no_items} {paneer butter masala|dish}`

and `sys_number` has two roles `no_ppl,no_items`

training data in intent **order** looks like:

```
order {one|sys_number|no_items} {paneer butter masala|dish}
order {3|sys_number|no_items} {taco salads|dish}
order {5|sys_number|no_items} {butter naan|dish}
order {two|sys_number|no_items} {virgin mojito|dish}
order {five|sys_number|no_items} {tomato soup|dish}
```

**Comment by serapio** [comment]
Why do you need the role label if it can be determined from the intent label? This design adds work to maintaining the annotation, while dialogue manager logic could just use the existing intent and entity labels.

**Comment by sameerg07** [comment]
You should have role labels as well on the dialogue manager. At any point
of time, as an end user, it's not clear why it isn't classifying even
though there is a role. And coming to dialogue manager, flexibility of role
classification is also important I feel
