### ISSUE TITLE
Cannot train entity recognition model?

### ISSUE THREAD

**Issue by derekmpham** [cisco/mindmeld#217]
I attempted to train the models, but see that I am unable to train the entity recognition model?

I first noticed this when I to train all the NLP classifiers (i.e. `NaturalLanguageProcessor.build()`), as seen in the following screenshot:

<img width="799" alt="Screen Shot 2020-08-27 at 4 35 20 PM" src="https://user-images.githubusercontent.com/16676809/91505323-2c9c7680-e884-11ea-808a-f29039a308a8.png">

________

I then tried to just focus on training an entity recognition model (i.e. `EntityRecognizer.fit()`), as seen in the screenshots below:

<img width="626" alt="Screen Shot 2020-08-27 at 2 35 30 PM" src="https://user-images.githubusercontent.com/16676809/91505693-10e5a000-e885-11ea-9bac-df716a6dfcef.png">

<img width="442" alt="Screen Shot 2020-08-27 at 2 35 41 PM" src="https://user-images.githubusercontent.com/16676809/91505710-1cd16200-e885-11ea-8e2b-049e5645135b.png">

, but am not getting any results. Any advice or suggestions on how to fix this?

Thank you! 🙏🏻

**Comment by minhtuev** [comment]
Blueprint app: https://github.com/CiscoDevNet/mindmeld-blueprints/pull/16

**Comment by minhtuev** [comment]
![image](https://user-images.githubusercontent.com/1332283/93278538-d5e6d600-f779-11ea-92ca-123da594c9e0.png)
Hi Derek, your config file is misconfigured so that's why the entity recognizer cannot train because they cannot find any train file. Please check the PR for more info.
