### ISSUE TITLE
Getting errors when installing

### ISSUE THREAD

**Issue by SilverStrings024** [cisco/mindmeld#222]
When trying to run `pip3 install mindmeld` I get the errors listed below. Is there anything I can do to fix this? I followed the docs as writted for virtualenv installation. I've even tried installing scikit-learn directly (successfully) but it didn't help with this.
`
    ERROR: Command errored out with exit status 1:
     command: /home/matt/Desktop/code/python/ai/projects/RPI_AI/project_jarvis/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e40czwic/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e40czwic/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xg2l0c1r/install-record.txt --single-version-externally-managed --compile --install-headers /home/matt/Desktop/code/python/ai/projects/RPI_AI/project_jarvis/include/site/python3.8/scikit-learn
         cwd: /tmp/pip-install-e40czwic/scikit-learn/
    Complete output (598 lines):
   (...)
`
Another
`
    error: Command "g++ -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/matt/Desktop/code/python/ai/projects/RPI_AI/project_jarvis/lib64/python3.8/site-packages/numpy/core/include -c sklearn/svm/src/libsvm/libsvm_template.cpp -o build/temp.linux-x86_64-3.8/sklearn/svm/src/libsvm/libsvm_template.o -MMD -MF build/temp.linux-x86_64-3.8/sklearn/svm/src/libsvm/libsvm_template.o.d" failed with exit status 127
`
Final
`
ERROR: Command errored out with exit status 1: /home/matt/Desktop/code/python/ai/projects/RPI_AI/project_jarvis/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e40czwic/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e40czwic/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xg2l0c1r/install-record.txt --single-version-externally-managed --compile --install-headers /home/matt/Desktop/code/python/ai/projects/RPI_AI/project_jarvis/include/site/python3.8/scikit-learn Check the logs for full command output.
`
I'm using Fedora 32 Workstation (5.7.17-200.fc32.x86_64)

**Comment by minhtuev** [comment]
@SilverStrings024 : we have been seeing dependency issues with Python 3.8, so you should try to use an earlier version. Currently MM supports 3.5 (soon to be deprecated), 3.6, and 3.7.

**Comment by SilverStrings024** [comment]
Thank you, I'll try that.
