### ISSUE TITLE
Change default system entity recognizer

### ISSUE THREAD

**Issue by ritvikshrivastava** [cisco/mindmeld#224]
In case an ``app_path`` is not provided while creating query factory, the system defaults to a NoOp SER, this causes a return of a NoneType SER object if the argument is missed. Instead of this, we can default to the duckling-based SER still so that the query factory can be independently called without passing an app_path or associating that SER service with only an app.

https://github.com/cisco/mindmeld/blob/67f635ae0d55f9761e31470c800755a1cd8bc972/mindmeld/query_factory.py#L170

To illustrate:

```
from mindmeld.query_factory import QueryFactory
from mindmeld.markup import load_query


qf = QueryFactory.create_query_factory()
query = "number {10|sys_number}"
load_query(markup=query, query_factory=qf, domain="a_domain")
```

Will raise: AttributeError: 'NoneType' object has no attribute 'entity'

This happens because the NoneType SER object is called by the annotation processing function regardless in 
markup.py https://github.com/cisco/mindmeld/blob/67f635ae0d55f9761e31470c800755a1cd8bc972/mindmeld/markup.py#L317

@KKsharma99

**Comment by minhtuev** [comment]
Who is calling attribute entity?

**Comment by ritvikshrivastava** [comment]
It's being called by system entity annotation processing function in ``mindmeld/markup.py`` 
https://github.com/cisco/mindmeld/blob/67f635ae0d55f9761e31470c800755a1cd8bc972/mindmeld/markup.py#L317

**Comment by minhtuev** [comment]
I see, we just need to change this for QueryFactory right?

**Comment by ritvikshrivastava** [comment]
Yes, but instead of defaulting to NoOp, shouldn't we default to duckling as that's what most MM apps use?

**Comment by minhtuev** [comment]
@ritvikshrivastava: we want to decouple MindMeld from Duckling, so the NoOp should be the default option
