### ISSUE TITLE
Add Screening Blueprint

### ISSUE THREAD

**Issue by minhtuev** [cisco/mindmeld#243]
We should add the health screening blueprint, which is in Spanish, to our MindMeld package and also add a documentation page as well

https://github.com/CiscoDevNet/mindmeld-blueprints/pull/22

**Comment by jjjacksn** [comment]
Looks like we partially completed this. There are now docs, but `mindmeld blueprint screening_app` fails.

**Comment by vijay120** [comment]
Its done.
