### ISSUE TITLE
How to deploy Mindmeld project with production server mode?

### ISSUE THREAD

**Issue by LL0814** [cisco/mindmeld#249]
The documentation explains how to run the service locally, but it does not explain how to deploy to the production server. I tried using a new flask service to call Mindmeld app. Although the service started successfully, it didn't load any data. Can you tell me how to deploy to the production?

![image](https://user-images.githubusercontent.com/30402958/95532890-51077900-0a14-11eb-9c0e-e4b64d9f8aa8.png)

**Comment by minhtuev** [comment]
What is the mode of error that you are seeing? Have you tried to see if `app.app_manager.parse` is working correctly?

Btw we are trying a new method to create the MindMeld forum: if you can repost this question on StackOverflow with the mindmeld tag (https://stackoverflow.com/questions/tagged/mindmeld), we will try to answer on there - much appreciated!

This conversation might be useful to others too 👍

**Comment by LL0814** [comment]
![image](https://user-images.githubusercontent.com/30402958/95534707-1522e280-0a19-11eb-9535-2135b2d96307.png)

No error message😊.

**Comment by minhtuev** [comment]
Try this:
```
from mindmeld import configure_logs
configure_logs()
```

Let me know if this shows more error messages

**Comment by LL0814** [comment]
![image](https://user-images.githubusercontent.com/30402958/95550248-2aa90400-0a3b-11eb-8728-3a0fa5a8933d.png)


Is it used like this? It doesn't seem to be working.

**Comment by minhtuev** [comment]
what's the query text? is this an async app?

**Comment by LL0814** [comment]
It’s a sync app, and the query text is “hi”.

**Comment by LL0814** [comment]
Hi, @minhtuev can you please provide a way to deploy with production mode?

**Comment by LL0814** [comment]
Hi, @minhtuev 
I'm sure I didn't do anything, but the server is working for me😊. The server code is the same as the code in the picture in my question, and start it with gunicorn.  Thx for your help.

![image](https://user-images.githubusercontent.com/30402958/95975123-5c113d80-0e48-11eb-9ee0-5284857e5b06.png)
