### ISSUE TITLE
GoogleTranslate.translate() adds "a.m." when translating a sentence with a time reference.

### ISSUE THREAD

**Issue by KKsharma99** [cisco/mindmeld#269]
When translating a sentence with Google translate, "a.m." is added to the translation. This assumption can change the meaning of the original sentence. When duckling parses these sentences, it often assumes "pm".

Example: "est-ce que la salle est libre à 9:30"
Translation: "is this room free at 9:30 a.m." 

Example: "cette salle de réunion est-elle libre à 2 heures"
Translation: "is this meeting room free at 2 **a.m.**"

Example: "la salle de réunion est-elle disponible à 11:30"
Translation: "is the meeting room available at 11:30 **am**"

Example: "cette salle est-elle disponible entre 4 heures et 6 heures"
Translation: "is this room available between 4 **a.m.** and 6 **a.m.**"

**Comment by vijay120** [comment]
Closing since this is a google translate issue.
