### ISSUE TITLE
Decouple ES from MindMeld

### ISSUE THREAD

**Issue by minhtuev** [cisco/mindmeld#29]
1. We can map to an external ES endpoint
2. ES should not be a requirement to run MindMeld?

**Comment by minhtuev** [comment]
https://github.com/cisco/mindmeld/pull/44

**Comment by minhtuev** [comment]
This PR makes ES optional if there is no mapping.json

https://github.com/cisco/mindmeld/pull/185

**Comment by arushir** [comment]
@minhtuev ES is already optional for the Entity Resolver as described [here](https://www.mindmeld.com/docs/userguide/entity_resolver.html#about-the-exact-match-text-similarity-model).

#185 makes it so that ES is not called by default if the mapping.json file is not populated

**Comment by minhtuev** [comment]
Host the doc change here: https://cisco.github.io/mindmeld/userguide/optional_dependency.html
