### ISSUE TITLE
Add a new feature for instructed KB : multiple questions & answers

### ISSUE THREAD

**Issue by warrior13reg** [cisco/mindmeld#291]
Good afternoon dear colleagues,

I am writing to you with a proposal to make your solution a little bit flexible, especially when we make out "kb" with instructed data.

In your current version, for one id I can add one question and one answer like:

{
"id": "001",
"question": "What is the weather like today?",
"answer"  : "It's fine."
}

But we know that each of us can give different variants of the same question and possible answers to that question. 

If you deploy the following feature it will make your solution more flexible. The example:

{
"id": "001",
"question": (["What is the weather like today?", "Can you tell me about the weather in your place?"]), and so on
"answer": (["The weather is fine", "It's been unbroken sunshine"]) and so
}

Of course, there will be situations that we won't manage to put all possible Q&A for one topic but it will give to a bot more opportunities to maintain topics by giving different variants of answers and they will be more relevant without making out a huge "kb" of instructed data.

I hope you will look through my proposal and find it adequate. 

Have a nice day.

**Comment by vijay120** [comment]
@murali1996 Wanted to get your inputs on this as you work on the entity resolution/QA features

**Comment by warrior13reg** [comment]
Hi, what I have got to do?

**Comment by murali1996** [comment]
Hi @warrior13reg, thanks for the feedback and the proposal. The idea of allowing lists of strings in knowledge base fields definitely can aid in making the database compact. Will try to take this up in [PR 297](https://github.com/cisco/mindmeld/pull/297) or in a follow-up PR.

**Comment by murali1996** [comment]
Support added through PR #297. Note that this functionality cannot be used when using Elasticsearch backed question answerer but can be used with other backend choice. To use this feature, clone the latest MindMeld through [git clone](https://github.com/cisco/mindmeld). For docs related to different QuestionAnswerer backends, [make docs from the clone](https://github.com/cisco/mindmeld) and checkout the docs section- _Working with the Knowledge Base and Question Answerer_.
