### ISSUE TITLE
How to set question_answering model configuration

### ISSUE THREAD

**Issue by Harirupa** [cisco/mindmeld#308]
Hi support team,

I am new to Mindmeld and new to OOP as well.
Trying to follow through the blueprint example to understand the Mindmeld package with an intention to create a simple conversational bot for educational modules.

Can someone help me with setting up of question_answering model configuration. When I use the following code I get an error message saying "No question_answering model configuration set. Using default."
_Code snippet -
"from mindmeld.components import QuestionAnswerer
qa = QuestionAnswerer(app_path='kwik_e_mart')
qa.load_kb(app_namespace='kwik_e_mart', index_name='stores', data_file='kwik_e_mart/data/stores.json')"_

How do I provide the application path to upload embeddings as specified in the app config? 
Alternatively, how do I directly provide the QA config?

Familiar with OOP but this is the first time applying it for a project.
Any help is much appreciated.
Rupa

**Comment by murali1996** [comment]
Hi @Harirupa,

I think what you are seeing is a progress information from the logger and not an error. In your case, you haven't specifically passed in any Question-Answerer config while loading KB, nor is a configuration available in `kwik_e_mart/config.py`. Hence, the a default config (`{"model_type": "keyword"}`) which is based on Elasticsearch service is used; that's what the logger info is about.

You can either pass-in configurations through _config_ parameter in `load_kb` as well as in `QuestionAnswerer` as:
```
config = {"model_type": "keyword"}
qa = QuestionAnswerer(app_path='kwik_e_mart', config=config)
qa.load_kb(app_namespace='kwik_e_mart', index_name='stores', data_file='kwik_e_mart/data/stores.json', config=config)
```
or    
add the following to the `kwik_e_mart/config.py` file
```
QUESTION_ANSWERER_CONFIG = {"model_type": "keyword"}
```

For more choices of configuration, please take a took at the docs: <https://www.mindmeld.com/docs/userguide/kb.html>

**Comment by Harirupa** [comment]
Hello Murali,
Thank you so much for your time and help.
I am able to now configure the kb successfully.

As a follow up step, I would like to modify the blueprint kb with specific
data relevant to our project. The issues I might encounter are most likely
going to be due to lack of my familiarity with the processes and I don't
wish to populate the Github/issues space with my general questions.

I was wondering if there was a Mindmeld forum/community where I can post my
general queries to seek assistance (something similar to StackOverflow)?

Any suggestions would be much appreciated.

Regards,
Rupa

**Comment by murali1996** [comment]
HI @Harirupa , you can post your questions on the stackoverflow tag https://stackoverflow.com/questions/tagged/mindmeld

**Comment by Harirupa** [comment]
I have posted my query on stackoverflow (https://stackoverflow.com/questions/67684026/mindmeld-elasticsearch-index-and-questionanswerer) and hope to get a response soon.

**Comment by murali1996** [comment]
Hi @Harirupa, I see a response to your question on stackoverflow. You can keep posting more questions in that space. I'm closing this Issue for now. Feel free to re-open it if you would like to bring up something else.
