### ISSUE TITLE
Frame is immutable when passed in through the "/parse" route

### ISSUE THREAD

**Issue by rfinz** [cisco/mindmeld#316]
The Marshmallow Schema.load method in the "/parse" route of the server produces a `immutable.Map` for `request.frame`, which is then passed into the DialogueResponder object, and becomes `response.frame`. This is not a problem if `frame` is left empty on the request, since then DialogueResponder class supplies `{}` as the default.

As a result, attempts to modify the response's frame inside of a handler (but ONLY AFTER FRAME VALUES ARE PROVIDED IN THE REQUEST JSON) will fail.

**Proposed solution:**
https://github.com/cisco/mindmeld/blob/e5601da8441f4af73e4535b7d02813f91cdf5139/mindmeld/app_manager.py#L152
in the pre-dialogue manager prep function, convert the `immutable.Map` to a dict before passing to the response object.
i.e. `frame=dict(frame)` in the line above.

I was able to test locally and confirmed that this worked from tag 4.3.4

**Comment by vijay120** [comment]
@vrdn-23 Assigning this to you

**Comment by vrdn-23** [comment]
@rfinz The fix for this has been merged. Thank you for raising the issue!
