### ISSUE TITLE
Leveraging semantic embeddings

### ISSUE THREAD

**Issue by Harirupa** [cisco/mindmeld#347]
Hi there,
Just wondering if you someone can help me configure the bert-base-cased pre-trained model for unstructured text data (to create question answering type faq bot based on hr_assistant blueprint).

How do I pass in the parameters as I would like the tokenizer to be as follows.
tokenizer=AutoTokenizer.from_pretrained("bert-base-cased").

The default 'bert-base-nli-mean-tokens' is unable to extract features useful for my question answering tasks.

I tested the bert-base-cased model with AutoTokenizer and it works perfectly fine for my faq data set however, I am unable to configure the same in the MindMeld framework.

Is there an example blueprint that leverages custom_embedders. I have seen the documentation on how to register a class for use with MindMeld via the register_embedder method, however, it would be great if you can provide any example cases. 
Any help in this regard is much appreciated.
Regards,
Rupa

**Comment by murali1996** [comment]
Hi @Harirupa, you can find the option to pass-in your choice of BERT name in the latest releases on Mindmeld. The official docs you see at <https://www.mindmeld.com/docs/index.html> might not have few pieces of information updated. 

You can get the latest version either by doing ```git clone https://github.com/cisco/mindmeld``` or from the [release candidates](https://github.com/cisco/mindmeld/releases). (If you want to get the latest docs, you can then follow the couple of steps mentioned [here](https://github.com/cisco/mindmeld#documentation))

In the latest versions, there is a slight modification to the format of QUESTION_ANSWERER_CONFIG. An example config with required keys for your use-case is below:

```
QUESTION_ANSWERER_CONFIG = {
   "model_type": "elasticsearch",  # although recommended to use elasticsearch, if you wish not to use elasticsearch for some reason, specify 'native'
   "model_settings": {
       "query_type": "embedder_text",  # previously passed-in as model_type
       "embedder_type": "bert", 
       "pretrained_name_or_abspath": "bert-base-cased",  # any valid name from https://huggingface.co/models or https://www.sbert.net/docs/pretrained_models.html
       "bert_output_type": "mean", # if you wish to use mean-pooled output from BERT's output, other choices: "cls" (same as BERT's convention)
       "quantize_model": False,  # True if you wish use a quantized BERT for inference time speed-ups
       "embedding_fields": {
           ...
       }
   }
}
```
Here, when you pass the name 'bert-base-cased', we load the tokenizer of 'bert-base-cased' only through the AutoTokenizer. We do not use any other tokenization technique.

Hope this resolves your issue.

**Comment by Harirupa** [comment]
Hello Murali,

Thanks for attending to my query. I used the configuration you suggested
but I am receiving an error message ValueError: Invalid model
configuration: Unknown embedder type 'bert'

qa = QuestionAnswerer(app_path=bp_name, config=QUESTION_ANSWERER_CONFIG)  -
No problem

However, while loading kb, it gives me the above error message.
qa.load_kb(app_namespace=bp_name, index_name=bp_name,
data_file='hr_assistant/data/hr_faq_data.json', app_path='hr_assistant',
config=config, clean = True)

The following parameters were passed in as suggested
QUESTION_ANSWERER_CONFIG = {
   "model_type": "elasticsearch",  # although recommended to use
elasticsearch, if you wish not to use elasticsearch for some reason,
specify 'native'
   "model_settings": {
       "query_type": "embedder_text",  # previously passed-in as model_type
       "embedder_type": "bert",
       "pretrained_name_or_abspath": "bert-base-cased",  # any valid name
from https://huggingface.co/models or
https://www.sbert.net/docs/pretrained_models.html
       "bert_output_type": "cls", # if you wish to use mean-pooled output
from BERT's output, other choices: "cls" (same as BERT's convention)
       "quantize_model": False,  # True if you wish use a quantized BERT
for inference time speed-ups
         "embedding_fields": {
            "hr_faq_data": ["question", "answer"]
        }
   }
}

Once this works, I am thinking of passing in the parameter
"clf":"pipeline(question-answering)" for the model to use
question-answering feature.
Thanks once again for your time and help.

Regards,
Rupa

**Comment by murali1996** [comment]
Hi @Harirupa, looks like you do not have required libraries installed. Can you try again upon installing the extra _bert_ requirements? You can do that by running ```pip install mindmeld[bert]``` (if bash else if zsh, then ```pip install "mindmeld[bert]"```). Let me know if that helps resolve your issue.


Regarding your last comment:
The QA module does not use a key called _"clf"_. Are you looking to pass-in some particular config key-value pair to the huggingface's AutoModel/AutoTokenizer? Or are you planning to use a pretrained_model named _"pipeline(question-answering)"_.

**Comment by Harirupa** [comment]
In addition to my earlier email,
When I configure with  {"model_type": "embedder-text"}), as I did
previously, I don't have any problem but classifiers do not resolve my
query appropriately, unless there is an exact match to the question text.
If required I can forward you a sample question answer pipeline I created
using 'bert-base-cased' with open source models so that you understand my
use case.

I also tried the following  when I received the value error stated earlier.
Could this version incompatibility be an issue?
Although the requirement was already fulfilled, I tried downloading 'bert'
again using !pip install mindmeld[bert] and received the following message

ERROR: transformers 3.5.1 has requirement sentencepiece==0.1.91, but
you'll have sentencepiece 0.1.96 which is incompatible.

Similarly, tried updating tensorflow with #!pip install
mindmeld[tensorflow] but got the error message,

ERROR:
Could not find a version that satisfies the requirement
tensorflow<2.0,>=1.13.1; python_version >= "3.7"
and extra == "tensorflow" (from mindmeld[tensorflow]) (from
versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1,
2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2,
2.3.3, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0,
2.4.1, 2.4.2, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0,
2.6.0rc0, 2.6.0rc1)

ERROR: No matching distribution found for tensorflow<2.0,>=1.13.1;
python_version >= "3.7" and extra == "tensorflow" (from
mindmeld[tensorflow])

Apologies for any interruptions but there is not enough Mindmeld community
to respond to my queries on "stackoverflow".

Regards,

Rupa

**Comment by murali1996** [comment]
@Harirupa ,

Regarding your first point: 
- just to confirm that you are using ```{"model_type": "embedder_text"}``` and not ```{"model_type": "embedder-text"}``` (_ vs. -)
- can you try using ```{"model_type": "embedder"}``` and see if your get desired results

For the install errors, I would suggest:
- uninstall torch, transformers , sentencepiece, sentence-transformers as well as tensorflow and then install extra _bert_ requirements by running `pip install mindmeld[bert]`. Looks like you already have some version of some of these libraries which is causing such installation errors.
- tensorflow is not required for using bert based embedders in QuestionAnswerer, so the above command won't install it

Let me know if doing so resolves your errors.

**Comment by Harirupa** [comment]
Thank you so much for looking into this for me.

I have uninstalled as you suggested and installed extra bert requirements
using pip install mindmeld[bert]. I don't have any errors.

When I loaded the kb, the bert model was downloaded (hurray - 405M
parameters downloaded).

However, I received the message saying : No bert model specifications
passed, using default.

I tried using {"model_type": "embedder"} but no change in the result.

I want to replicate the process of creating a classifier using
question-answering (clf = pipeline(question-answering) from the
huggingface's AutoModel/AutoTokenizer model. Please see attached image
files for more details on what I am trying to achieve.

I am open to using any of the data sets such as CoQA
<https://arxiv.org/pdf/1808.07042.pdf> (Conversational Question Answering
data-set released by Stanford NLP in 2019) or anything that is useful for
creating an intelligent QA conversational interface.

With default embedder_text model type, Mindmeld app can respond to
questions that match the exact text in the question/answer.

For example

question = 'what is the goal of sdg5?' and mindmeld responds with
appropriate response of "The goal of sdg5 is to achieve gender equality and
empower all women and girls"

However, if I rephrase the question to "which goal talks about gender
equality?" it goes to unsupported intent and provides the default response
of "Hmm, I don't quite understand,.... ". Whereas the pretrained
bert-base-cased could answer this without fail. There are some limitations
to this model such as bias and token limit (I think 512) etc., but it seems
to serve the purpose very well.

It would be great if you could help me configure any of the bert models to
achieve better results.

Thanks.

Rupa










Yes, I am using embedder_text (with _).

**Comment by murali1996** [comment]
> However, I received the message saying : No bert model specifications
passed, using default.

Looks like you are using an older version of MindMeld. Like i suggested in the [first comment](https://github.com/cisco/mindmeld/issues/347#issuecomment-890256940), only the latest version allows you to pass different model names of bert.

> Please see attached image
files for more details on what I am trying to achieve.

I am unable to find your attachments. Can you send them again?

> However, if I rephrase the question to "which goal talks about gender
equality?" it goes to unsupported intent and provides the default response
of "Hmm, I don't quite understand,.... ".

This is happening because your input is being classified as `intent='unsupported'` by the NaturalLanguageProcessor. Assuming your main goal is to use the QuestionAnswerer alone to answer the user's questions, I would suggest you can create a minimalistic app that directs all user intents to use the QuestionAnswerer. Meaning, you do not have to have domain-intent-entities hierarchical data to access question answerer; you can by-pass the NaturalLanguageProcessor if that's what makes it easier for you to address many out-of-domain inputs. Here is a skeleton of the code snippet that does the job:

In the `config.py`, you can just specify the QA config and nothing else
```
QUESTION_ANSWERER_CONFIG = {
   "model_type": "elasticsearch",
   "model_settings": {
       "query_type": "embedder",
       "embedder_type": "bert", 
       "pretrained_name_or_abspath": "bert-base-cased",
       "bert_output_type": "mean",
       "quantize_model": False,
       "embedding_fields": {
           ...
       }
   }
}
```

In the `faq.py` file, do the following:
```python
from .root import app

@app.handle(default=True)
def greet(request, responder):
    query = request.text
    # do your retrieval with question_answerer and query, an example snippet below
    search_results = app.question_answerer.get(question=query, answer=query)
    return search_results[0]["answer"]
```

And then run the app as usual.

**Comment by Harirupa** [comment]
I am not comfortable with cloning as I ran into problems with permissions. See below -
> (Cloning into 'mindmeld'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights and the repository exists.)

**Instead, I have upgraded the package using pip install mindmeld --upgrade. Not sure if that is upgrading to the required level.**

I am going to re-install mindmeld again and try your suggestions of creating a minimalistic app (which should suffice my requirement for now).
Here are the attachments again.
![bert_base_cased_trail_output](https://user-images.githubusercontent.com/37388514/128120311-ee03c8a2-fa27-4116-958c-001b7e78ae1b.png)
![Question_answerer_config_bert](https://user-images.githubusercontent.com/37388514/128120530-09d87aa1-a371-425f-a848-89751d020ff3.png)

**Comment by Harirupa** [comment]
Can you please help me install the latest version. 
I cloned the repo successfully and it created a local folder with name mindmeld.
Appended PYTHONPATH with new directory path.
I created a new env with conda and activated the new environment in the new mindment directory.
Installed jupyter in the new folder so that it runs in the new env.
However, when I install mindmeld, it's using cached version 4.3.4
I believe the new version is 4.3.5.
I couldn't solve the problem of passing in bert model specifications.
It can't even find the bert model now.
My contact email is rupaperth@gmail.com
I really need to get this done for my project and truly appreciate any help. Thanks you so much.
I am located in Australia (Perth) and work for Curtin University as our group is keen to use Cisco mindmeld. Thanks so much for your support.
Regards,
Rupa

**Comment by murali1996** [comment]
You can do `pip install mindmeld==4.3.5rc11` or if you are doing through git clone, then from inside the cloned folder, do `pip install -e .`. If doing the former, install extras by running `pip install mindmeld[bert]`. If doing the latter, you can do `pip install -e .[bert]`

**Comment by Harirupa** [comment]
Thank you so much. I am able to use the latest mindmeld with above instructions.
Regards,
Rupa
