### ISSUE TITLE
model_type native for KB

### ISSUE THREAD

**Issue by Harirupa** [cisco/mindmeld#360]
Using model_type": "native" for KB configuration resolved the issues of ambiguity in the response to some queries, however, unable to link to default greet handler. Is it required to initiate the question_answerer again? 
Could someone provide more information on how to use 'native' model_type for KB configuration. Thanks

**Comment by murali1996** [comment]
> however, unable to link to default greet handler. Is it required to initiate the question_answerer again?

Yes, you are correct. In case of _native_ question-answerer, you'll have to call load_kb method as shown below along with loading nlp models. In case of _elasticsearch_ question-answerer, you just have to do it only once and don't have to load_kb when loading models, whereas in case of _native_ question-answerer, you'll have to do load_kb every time you load nlp models. 

PS: We are working on bringing _native_ question-answerer akin to _elasticsearch_ question-answerer when it comes to loading-kb only during the building phase. PR for this is available at: https://github.com/cisco/mindmeld/pull/341.

```
from mindmeld.components import Conversation
from mindmeld.components import NaturalLanguageProcessor
from mindmeld.components import QuestionAnswerer

# load knowledge bases that you would like to use in the app
QuestionAnswerer(app_path="./hr_assistant").load_kb(
    index_name="hr_faq_data",
    data_file="./hr_assistant/data/hr_faq_data.json",
    clean=False)

# build models for intent classification
nlp = NaturalLanguageProcessor("./hr_assistant")
nlp.load()

# run the app (see handlers defined in the app's __init__.py file)
conv = Conversation(nlp=nlp, app_path="./hr_assistant")
print(conv.say("hello")[0])
print(conv.say("summary mission info")[0])
```

**Comment by Harirupa** [comment]
Hello @murali1996,
Unfortunately, couldn't resolve the issue of default greeting. I have shared my app folder and notebook through email. Please review and advice. Thanks.

**Comment by murali1996** [comment]
See PR #341
