### ISSUE TITLE
installing mind meld

### ISSUE THREAD

**Issue by ngoiyaeric** [cisco/mindmeld#465]
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects

**Comment by ngoiyaeric** [comment]
I get this error when I 'pip install mindmeld'

**Comment by ngoiyaeric** [comment]
[end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects

**Comment by serapio** [comment]
@ngoiyaeric What is your python version and sys.platform?

**Comment by ngoiyaeric** [comment]
I'm running x86_64 architecture on mac os with python 3.11.3

**Comment by serapio** [comment]
Aha. 3.11 is not supported yet. Try running `pip install mindmeld==4.7.0rc2` in python 3.9.

**Comment by ngoiyaeric** [comment]
I'm now getting the following error
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement torch~=1.10.0; python_version >= "3.6" (from mindmeld) (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch~=1.10.0; python_version >= "3.6"

**Comment by serapio** [comment]
That looks like you're still using python 3.11. It should find torch==1.10.2.

**Comment by ngoiyaeric** [comment]
For future users that encounter this issue, this fixed it for me ;) 

Consider installing pyenv with Homebrew on macOS

brew update
brew install pyenv
OR Clone the repository to get the latest version of pyenv

 git clone https://github.com/pyenv/pyenv.git ~/.pyenv
Define your environment variables (For a recent MacOS you may want to replace ~/.bash_profile with ~/.zshrc as that is the default shell)

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
source ~/.bash_profile
Restart your shell so the path changes take effect

exec "$SHELL"
Verify the installation and check the available python versions

pyenv install --list
Install the required python version

pyenv install 3.9
Set it as your global version after installation

pyenv global 3.9
eval pyenv path

eval "$(pyenv init --path)"
Verify your current python version the system is using

python3 --version
