### ISSUE TITLE
Fix Step 5 in the documentation (missing id field?)

### ISSUE THREAD

**Issue by tbassetto** [cisco/mindmeld#52]
I was following the tutorial today with mindmeld 4.1.6 and python 3.7.4 on macOS.

The part of [Step 5](https://www.mindmeld.com/docs/quickstart/05_create_the_knowledge_base.html) where it says to type `qa.load_kb('my_app', 'stores', './data/stores.json')` fails with:
```
  File "/Users/thobasse/.virtualenvs/mindmeld/lib/python3.7/site-packages/mindmeld/components/question_answerer.py", line 234, in transform
    base = {'_id': doc['id']}
KeyError: 'id'
```
I suppose that the code now expects our data to contain an `id` field, which is not the case of the JSON data file given as an example above.

**Comment by minhtuev** [comment]
You are right the `id` field is included in our json data file
https://github.com/cisco/mindmeld/blob/master/tests/kwik_e_mart/data/stores.json

**Comment by minhtuev** [comment]
Addressed in the PR.
