### ISSUE TITLE
Remove Elasticsearch as hard dependency for Question Answer / Make QA pluggable

### ISSUE THREAD

**Issue by mingfang** [cisco/mindmeld#87]
Currently the QuestionAnswerer requires Elasticsearch to work but I would like to use something else.  
Please make the QuestionAnswerer pluggable so that we choose different implementations.
For example, it would be great to have a "in-memory" implementation for tests or very small QuestionAnswerer.  Or use another search engine such as Solr.

**Comment by minhtuev** [comment]
Yes we are working on an alternative to ES.

**Comment by minhtuev** [comment]
@mingfang : as we are reviewing the existing architecture, have you made any progress? How is your current experience with MM?

**Comment by minhtuev** [comment]
Currently, this issue is being addressed by https://github.com/cisco/mindmeld/issues/29

**Comment by minhtuev** [comment]
We have made the changes to make ES optional and documented it here:
https://cisco.github.io/mindmeld/userguide/optional_dependency.html
